# Generated by Django 3.2.4 on 2021-06-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrevision',
            old_name='content',
            new_name='contentid',
        ),
    ]
