# Generated by Django 3.2.4 on 2021-06-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_content_bookrevision_contentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcontent',
            old_name='content',
            new_name='contentfield',
        ),
        migrations.RenameField(
            model_name='bookrevision',
            old_name='contentid',
            new_name='content',
        ),
    ]
