# Generated by Django 3.2.4 on 2021-06-18 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookcontent_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrevision',
            name='content',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_revision_content', to='book.bookcontent'),
        ),
    ]
