# Generated by Django 3.2.4 on 2021-06-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('book', '0006_auto_20210618_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontent',
            name='modifiedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.user'),
        ),
    ]
