# Generated by Django 3.2.4 on 2021-06-18 09:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('isPublished', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('docId', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Google Doc ID')),
                ('revisionCode', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contentfield', models.TextField(blank=True, default='', null=True, verbose_name='Book Content (JSON)')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_content_meta', to='book.book')),
                ('modifiedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
        ),
        migrations.CreateModel(
            name='BookRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=30, verbose_name='Author')),
                ('publisher', models.CharField(blank=True, max_length=30, verbose_name='Publisher')),
                ('isPublished', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_revision_content', to='book.bookcontent')),
                ('modifiedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
        ),
        migrations.AddField(
            model_name='bookcontent',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_content_revision', to='book.bookrevision'),
        ),
        migrations.AddField(
            model_name='book',
            name='latest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_content', to='book.bookrevision'),
        ),
        migrations.AddField(
            model_name='book',
            name='modifiedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.user'),
        ),
    ]
